
services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8085:8080"
      - "50000:50000"
    
    environment:
      JENKINS_OPTS: --prefix=/jenkins

volumes:
  jenkins_home: