pipeline {
    agent any
    stages {
        stage('Clone repository') {
            steps {
                git credentialsId: 'github-credentials', url: 'https://github.com/ouiamch88/python-deployment.git'
            }
        }
        stage('Build Docker image') {
            steps {
                script {
                    docker.build('python-app')
                }
            }
        }
        stage('Deploy with Docker Compose') {
            steps {
                script {
                    sh 'docker-compose down'
                    sh 'docker-compose up -d'
                }
            }
        }
        stage('Tests') {
            steps {
                script {
                    sh 'docker-compose exec python_app pytest'
                }
            }
        }
    }
}

